

-- 기본키


-- 외래키


-- 시퀀스
DROP SEQUENCE REVIEWS_SEQ;
CREATE SEQUENCE REVIEWS_SEQ NOCACHE;

DROP TABLE REVIEWS;
CREATE TABLE REVIEWS(
    REVIEW_NO           NUMBER NOT NULL,
    REVIEW_TITLE        VARCHAR2(1000 BYTE) NOT NULL,
    REVIEW_WRITER       VARCHAR2(30 BYTE) NOT NULL,
    REVIEW_CONTENT      CLOB,
    REVIEW_CREATED_AT   TIMESTAMP,                     
    REVIEW_MODIFIED_AT  TIMESTAMP,
    REVIEW_HITS         NUMBER DEFAULT 0 NOT NULL
);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트1', '테스터1' , '테스트1', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트2', '테스터2' , '테스트2', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트3', '테스터3' , '테스트3', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트4', '테스터4' , '테스트4', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트5', '테스터5' , '테스트5', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트6', '테스터6' , '테스트6', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트7', '테스터7' , '테스트7', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트8', '테스터8' , '테스트8', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트9', '테스터9' , '테스트9', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트10', '테스터10' , '테스트10', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트11', '테스터11' , '테스트11', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트12', '테스터12' , '테스트12', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트13', '테스터13' , '테스트13', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트14', '테스터14' , '테스트14', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트15', '테스터15' , '테스트15', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트16', '테스터16' , '테스트16', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트17', '테스터17' , '테스트17', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트18', '테스터18' , '테스트18', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트19', '테스터19' , '테스트19', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트20', '테스터20' , '테스트20', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트21', '테스터21' , '테스트21', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트22', '테스터22' , '테스트22', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트23', '테스터23' , '테스트23', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트24', '테스터24' , '테스트24', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트25', '테스터25' , '테스트25', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트26', '테스터26' , '테스트26', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트27', '테스터27' , '테스트27', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트28', '테스터28' , '테스트28', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트29', '테스터29' , '테스트29', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트30', '테스터30' , '테스트30', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트31', '테스터31' , '테스트31', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트32', '테스터32' , '테스트32', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트33', '테스터33' , '테스트33', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트34', '테스터34' , '테스트34', SYSDATE, SYSDATE, 0);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL, '테스트35', '테스터35' , '테스트35', SYSDATE, SYSDATE, 0);

COMMIT;


	