DROP SEQUENCE PRODUCT_SEQ;
CREATE SEQUENCE PRODUCT_SEQ NOCACHE;

DROP TABLE PRODUCT;
CREATE TABLE PRODUCT (
    PROD_NO NUMBER NOT NULL PRIMARY KEY,
    PROD_NAME VARCHAR2(100 BYTE) NOT NULL,
    PROD_PRICE NUMBER,
    PROD_MADE_AT DATE
);